### ISSUE TITLE
how to compile for linux?

### ISSUE THREAD

**Issue by ItsMoonPy** [absoIute/Mega-Hack-v5#1]

**Comment by ad2017gd** [comment]
not sure if you can. its using windows.h

**Comment by Hexcede** [comment]
I don't believe this is possible without doing a full port to linux. This heavily relies on Windows code. You could _maybe_ use it with Wine but I have no idea how Wine will handle this.

**Comment by Cvolton** [comment]
Wine handles this fine provided you run it in the same prefix
