### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Syconic** [absoIute/Mega-Hack-v5#2]
How can I download this here? 

Edit: I'm on android

**Comment by ad2017gd** [comment]
download as zip and extract the "bin" folder

**Comment by Amar7136** [comment]
Ni hack ap tk boleh download pun


Pada Sel, 12 Nov 2019, 3:46 AM ad <notifications@github.com> menulis:

**Comment by zEpicPants** [comment]
This hack is specifically for the Steam version of the game.
