### ISSUE TITLE
SoUnD tHe AlArMs

### ISSUE THREAD

**Issue by Syconic** [absoIute/Mega-Hack-v5#3]
![Screenshot_20191211-130757_Chrome](https://user-images.githubusercontent.com/53888055/70652077-9a7e1080-1c17-11ea-8511-b75a88cb4486.jpg)
Um. Why is this. What is setting these off.

**Comment by Hexcede** [comment]
Reading the source code I can immediately tell this is because it modifies external process memory (geometry dash) but I haven't looked at too much. It's kinda up to you whether you trust it or not and I wouldn't run it at the moment.

**Comment by yEsPaP** [comment]
normal.
