### ISSUE TITLE
Only Works On Steam

### ISSUE THREAD

**Issue by Blainicorn** [absoIute/Mega-Hack-v5#37]
I heard that Mega Hack v5 ONLY works on steam, and I don't have steam GD, I have normal GD. Can you make it so Mega Hack v5 works on more places instead of just steam?
![Screenshot 10_23_2021 16_38_08](https://user-images.githubusercontent.com/93042228/138558776-fe75c5d5-1978-4bda-9be2-1d5ef8abc34f.jpg)

**Comment by ChocolateLOL** [comment]
it's supposed to work with 2.113, can be steam or pirate version

**Comment by Blainicorn** [comment]
> it's supposed to work with 2.113, can be steam or pirate version

I have 2.11

**Comment by simalei** [comment]
> > it's supposed to work with 2.113, can be steam or pirate version
> 
> I have 2.11

So it won't work.
