### ISSUE TITLE
Cutting Trail Effect Addition

### ISSUE THREAD

**Issue by Md915** [absoIute/Mega-Hack-v5#50]
I have a suggestion that ithought it would be cool, trail customization.
Hear me out, if this goes well it can be very powerful, you know how the trail cuts sometimes at higher refresh rates right? So we can add that in the icon customization, to like force the trail to cut itself, i think that would be very cool, or can also be as an extension, idk if there is an extension that already does that but if so lmk.
Edit: like force it to cut itself on 60hz or something, im not sure if it still cuts at 240hz, to get just the trail effect, not the physics
Like into mhv7 but i cant find where to put this on mhv7 issues

**Comment by Brain-Flooder** [comment]
Mhv7 suggestions [here](https://github.com/absolllute/Mega-Hack-Pro-Future/issues) I guess.

**Comment by Md915** [comment]
> Mhv7 suggestions [here](https://github.com/absolllute/Mega-Hack-Pro-Future/issues) I guess.

Ty bro i couldnt find the link
