### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by RickyHerald** [absoIute/Mega-Hack-v5#6]
I have visual studio on my pc, just dont know how to compile this.
Any help explaining how to compile this would be great.

( i know i can just open the mega hack.exe in the bin, but i jsut want to know how to compile it ;) )

**Comment by absoIute** [comment]
Compile with Qt dependencies

**Comment by nullptr448** [comment]
> Compile with Qt dependencies

Please elaborate

**Comment by ImSammy6** [comment]
Has anyone been able to do it?
